[project]
name = "nano"
version = "0.1.0"
classifiers = ["Private :: Do Not Upload"]
description = "A minimal django template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "django-allauth[socialaccount]>=65.11.1",
    "django-debug-toolbar>=6.0.0",
    "pydantic-settings>=2.10.1",
]

[tool.pyrefly]
python_interpreter = ".venv/bin/python"
[tool.pyrefly.errors]
missing-attribute = "warn"
